### ISSUE TITLE
Some functions are not implemented

### ISSUE THREAD

**Issue by naiij** [RMiyagusuku/wifi-localization#1]
The [Likelihood class](https://github.com/RMiyagusuku/wifi-localization/blob/master/Localization/sensormodel/likelihood.py#L12) is not completed, and it will cause that mcl node in rss pacakge cannot work properly.
It calls Likelihood.jointpdf [here](https://github.com/RMiyagusuku/ros-wifi-localization/blob/master/rss/src/rss/localization_server.py#L91)
And some other functions not implemented may cause problems.

**Comment by RMiyagusuku** [comment]
Fixed the issue with the likelihood class, I had it working with the ROS self_localization.launch from the [ros wrapper repo](https://github.com/RMiyagusuku/ros-wifi-localization) using an Ubuntu 14.04 clean install, let me know if it solved your bugs. 

Note: Also check the changes at the ros-wifi-localization repo, as it was also updated.
